### PR TITLE
Bump operator sdk v1.7.0

### PR DESCRIPTION
**Pull request by abdulhaseeb2**

### CODE REVIEW

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/e0f39fc9f9eed6978dea7ef1f39145ade10525d4/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/fd9cf80e957671cf471dd4a9d128430ecc89da8f/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/1d2651d92b693dd382ff0b62c416ceb41238870e/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/2fa7623289adb8d8cc7a890f3802392c8eaa55d5/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/d7f5ca75528fceb9900be8f1295ee5523e0979b6/checks) has Failed!

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-c8dbc2a7`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-b56a7463`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-d429e694`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-cd18626a`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-473b6f1c`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-65e6e6f4`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-f7fbab00`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-d2f061d5`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-b586a051`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-09f86df5`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-6f08c139`

**Comment by stakater-user** [comment]
@abdulhaseeb2 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-42-5edc192a`

**Review by ahmedwaleedmalik — APPROVED** [review]
LGTM

**Pull request merged**
