### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-23-4de122c1`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-23-85f36042`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-23-12c0d8d2`

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-23-c01ac300`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
