### PR TITLE
Add pipeline

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/9de50015f98d58fd1d83a4874da3e07326cace49/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/e65357f49b69e534d28a8d9bda2bf09209a27194/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/6bf564aa800c12884780f2e8cd22befc65c7c97d/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/07fab98553f4ce2ec8b941b616ab3ddc8e27f166/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/fe62da19982b349479f740d35860b39970cba52d/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/38d9c845f2b5dfe2c7b31359391ad6d5b598ea00/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/aa8728e9399e58a5b0c0e3b5da462f3c4178f892/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/aa8728e9399e58a5b0c0e3b5da462f3c4178f892/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/69e87e9274de23507d10bd92161e86e4dd771bbc/checks) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/af0858e250e8f2d6c9043940dd133e86d902829c/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/ae00a8157176ca9114862b81aab049ad1f9082f8/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/dfd7003f5025c5f3642091f0561beed18739a4db/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/4818a34982bc261e78a70be1c5309b3f87e94cc3/checks) has Failed!

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-2-cfce646d`

**Comment by stakater-user** [comment]
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-2-cfce646d`

**Review by rehanjaved237 — APPROVED** [review]

**Pull request merged**
